stages:
  - deploy

image: node:20-alpine

pages:
  stage: deploy
  script:
    - cd 'app version 2/figma_mockup'
    - npm install
    - npm run build
    - cd ../..
    - rm -rf public
    - mv 'app version 2/figma_mockup/dist' public
  artifacts:
    paths:
      - public
  only:
    - main
